from __future__ import annotations

from ..core import *


PAPER_TEX_PATH = ROOT / "paper_writing" / "paper.tex"
PAPER_FIGS_DIR = ROOT / "figs" / "main" / "quantitative"

PAPER_FIGURES = {
    "benchmark_level/within_family_model_vs_agent_summary.png": "within_family_model_vs_agent_summary.png",
    "benchmark_level/within_family_model_vs_agent_detail.png": "within_family_model_vs_agent_detail.png",
    "benchmark_level/benchmark_model_adjusted_effects.png": "benchmark_model_adjusted_effects.png",
    "benchmark_level/benchmark_agent_lift_heatmap.png": "benchmark_agent_lift_heatmap.png",
    "benchmark_level/terminus_delta_by_model_heatmap.png": "terminus_delta_by_model_heatmap.png",
    "benchmark_level/benchmark_headroom_by_domain.png": "benchmark_headroom_by_domain.png",
    "benchmark_level/benchmark_headroom_tier_summary.png": "benchmark_headroom_tier_summary.png",
    "benchmark_level/benchmark_similarity_clustered_heatmap.png": "benchmark_similarity_clustered_heatmap.png",
    "benchmark_level/benchmark_uniqueness_vs_coverage.png": "benchmark_uniqueness_vs_coverage.png",
    "benchmark_level/benchmark_effective_dimensionality.png": "benchmark_effective_dimensionality.png",
    "benchmark_level/benchmark_greedy_selection.png": "benchmark_greedy_selection.png",
    "task_level/task_similarity_benchmark_pair_heatmap.png": "task_similarity_benchmark_pair_heatmap.png",
    "task_level/task_hard_to_predict_ranked.png": "task_hard_to_predict_ranked.png",
    "task_level/task_best_representatives.png": "task_best_representatives.png",
    "task_level/task_reliable_difficulty_composition.png": "task_reliable_difficulty_composition.png",
    "harbormix/harbormix_selection_diagnostics.png": "harbormix_selection_diagnostics.png",
}


def copy_paper_figures() -> None:
    PAPER_FIGS_DIR.mkdir(parents=True, exist_ok=True)
    for src_rel, dst_name in PAPER_FIGURES.items():
        src = KEY_FIGURE_DIR / src_rel
        dst = PAPER_FIGS_DIR / dst_name
        if src.exists():
            shutil.copy2(src, dst)


_DIGIT_WORDS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four", "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def _tex_safe_name(name: str) -> str:
    return "".join(_DIGIT_WORDS.get(c, c) for c in name)


def _tex_cmd(name: str, value: str) -> str:
    safe_value = value.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
    return f"\\newcommand{{\\{_tex_safe_name(name)}}}{{{safe_value}}}"


def _fmt(x: float, decimals: int = 1) -> str:
    return f"{x:.{decimals}f}"


def _pct(x: float) -> str:
    return f"{100 * x:.0f}"


def write_paper_stats(study_tables: dict[str, pd.DataFrame], included_benchmarks: list[str], raw_benchmark: pd.DataFrame | None = None) -> None:
    family_summary = study_tables["benchmark_within_family_summary"]
    model_effects = study_tables["benchmark_model_adjusted_effects"]
    agent_effects = study_tables["benchmark_agent_adjusted_effects"]
    agent_lift = study_tables["benchmark_agent_lift_vs_terminus"]
    terminus_by_model = study_tables["terminus_delta_by_model"]
    headroom = study_tables["benchmark_headroom_by_domain"]
    selected_tasks = study_tables["harbormix_selected_tasks"]

    lines = [
        "% Auto-generated by habor-analyze — do not edit manually.",
        "% Re-generate: uv run habor-analyze studies",
        "",
        "% ── General ──",
        _tex_cmd("NumIncludedBenchmarks", str(len(included_benchmarks))),
        _tex_cmd("NumHaborMixTasks", str(len(selected_tasks))),
        _tex_cmd("NumModels", str(len(model_effects))),
        _tex_cmd("NumAgents", str(len(agent_effects))),
        "",
    ]

    # ── Within-family model vs agent ──
    lines.append("% ── Within-family: model vs agent effect ──")
    for _, row in family_summary.iterrows():
        fam = str(row["family"])
        me_mean = float(row["model_effect_mean"])
        ae_mean = float(row["agent_effect_mean"])
        ratio = me_mean / ae_mean if ae_mean > 1e-9 else float("inf")
        wins = int(row["model_wins"])
        total = int(row["total_benchmarks"])
        pct = 100 * wins / total if total > 0 else 0
        lines += [
            _tex_cmd(f"{fam}ModelEffectMean", _fmt(me_mean, 3)),
            _tex_cmd(f"{fam}AgentEffectMean", _fmt(ae_mean, 3)),
            _tex_cmd(f"{fam}ModelAgentRatio", _fmt(ratio, 1)),
            _tex_cmd(f"{fam}ModelWins", str(wins)),
            _tex_cmd(f"{fam}TotalBenchmarks", str(total)),
            _tex_cmd(f"{fam}ModelWinPct", f"{pct:.0f}"),
        ]
    lines.append("")

    # ── Adjusted effects span ──
    lines.append("% ── Adjusted effects ──")
    model_max = float(model_effects["adjusted_mean"].max())
    model_min = float(model_effects["adjusted_mean"].min())
    agent_max = float(agent_effects["adjusted_mean"].max())
    agent_min = float(agent_effects["adjusted_mean"].min())
    lines += [
        _tex_cmd("ModelEffectSpan", _fmt(model_max - model_min, 2)),
        _tex_cmd("AgentEffectSpan", _fmt(agent_max - agent_min, 2)),
        _tex_cmd("TopModel", str(model_effects.iloc[0]["model"])),
        _tex_cmd("TopModelEffect", _fmt(model_max, 2)),
        _tex_cmd("BottomModel", str(model_effects.iloc[-1]["model"])),
        _tex_cmd("BottomModelEffect", _fmt(model_min, 2)),
        _tex_cmd("TopAgent", str(agent_effects.iloc[0]["agent"])),
        _tex_cmd("TopAgentEffect", _fmt(agent_max, 2)),
        _tex_cmd("BottomAgent", str(agent_effects.iloc[-1]["agent"])),
        _tex_cmd("BottomAgentEffect", _fmt(agent_min, 2)),
    ]
    lines.append("")

    # ── Terminus agent lift ──
    lines.append("% ── Agent lift vs terminus-2 ──")
    for _, row in agent_lift.iterrows():
        agent = str(row["agent"]).replace("-", "")
        lines += [
            _tex_cmd(f"{agent}MeanDelta", _fmt(float(row["mean_delta_vs_terminus"]), 3)),
            _tex_cmd(f"{agent}WinRate", _pct(float(row["win_rate_vs_terminus"]))),
        ]
    lines.append("")

    # ── Best terminus deltas by model ──
    lines.append("% ── Terminus delta by model×agent (top pairs) ──")
    for _, row in terminus_by_model.iterrows():
        model_tag = str(row["model"]).replace("-", "").replace(".", "").replace("_", "")
        agent_tag = str(row["agent"]).replace("-", "").replace(".", "").replace("_", "")
        lines += [
            _tex_cmd(f"Terminus{model_tag}{agent_tag}Delta", _fmt(float(row["mean_delta_vs_terminus"]), 3)),
            _tex_cmd(f"Terminus{model_tag}{agent_tag}WinRate", _pct(float(row["win_rate_vs_terminus"]))),
        ]
    lines.append("")

    # ── Headroom summary ──
    lines.append("% ── Benchmark headroom ──")
    n_saturated = len(headroom[headroom["best_score"] >= 0.95])
    n_hard = len(headroom[headroom["best_score"] < 0.50])
    mean_best = float(headroom["best_score"].mean())
    lines += [
        _tex_cmd("NumSaturatedBenchmarks", str(n_saturated)),
        _tex_cmd("NumHardBenchmarks", str(n_hard)),
        _tex_cmd("MeanBestScore", _fmt(mean_best, 3)),
    ]
    lines.append("")

    # ── Per-domain headroom stats ──
    lines.append("% ── Per-domain headroom stats ──")
    domain_stats = []
    for domain, grp in headroom.groupby("domain"):
        n_sat = int((grp["best_score"] >= 0.95).sum())
        n_hrd = int((grp["best_score"] < 0.50).sum())
        mean_bs = float(grp["best_score"].mean())
        tag = str(domain).replace(" ", "").replace("&", "And").replace(",", "")
        lines += [
            _tex_cmd(f"Num{tag}Saturated", str(n_sat)),
            _tex_cmd(f"Num{tag}Hard", str(n_hrd)),
            _tex_cmd(f"Num{tag}Benchmarks", str(len(grp))),
            _tex_cmd(f"Mean{tag}BestScore", f"{100 * mean_bs:.0f}"),
        ]
        domain_stats.append((domain, mean_bs, n_sat, n_hrd, len(grp)))
    domain_stats.sort(key=lambda x: x[1])
    ordinals = ["One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten"]
    for rank_idx, (domain, mean_bs, _, _, _) in enumerate(domain_stats[:3]):
        word = ordinals[rank_idx]
        lines += [
            _tex_cmd(f"MostHeadroomDomain{word}", str(domain)),
            _tex_cmd(f"MostHeadroomDomain{word}Score", f"{100 * mean_bs:.0f}"),
        ]

    se = headroom[headroom["domain"] == "Software Engineering"]
    se_hard = se[se["best_score"] < 0.50].sort_values("best_score")
    lines.append("% ── SE hardest benchmarks (sorted by score) ──")
    for i, (_, row) in enumerate(se_hard.iterrows()):
        bname = benchmark_display_name(row["benchmark"])
        word = ordinals[i]
        lines += [
            _tex_cmd(f"SEHardBenchmark{word}", bname),
            _tex_cmd(f"SEHardBenchmark{word}Score", f"{100 * row['best_score']:.0f}"),
        ]
    lines.append("")

    # ── Effective dimensionality ──
    dim_stats = study_tables["benchmark_effective_dimensionality"]
    if not dim_stats.empty:
        d = dim_stats.iloc[0]
        lines.append("% ── Effective dimensionality ──")
        lines += [
            _tex_cmd("ParticipationRatio", _fmt(float(d["participation_ratio"]), 1)),
            _tex_cmd("ComponentsForNinety", str(int(d["n_components_90pct"]))),
            _tex_cmd("ComponentsForNinetyFive", str(int(d["n_components_95pct"]))),
            _tex_cmd("TopOneVariance", _pct(float(d["top1_variance"]))),
            _tex_cmd("TopThreeVariance", _pct(float(d["top3_variance"]))),
        ]
        lines.append("")

    # ── Domain correlation summary ──
    domain_corr = study_tables["benchmark_domain_correlation_summary"]
    within_row = domain_corr[domain_corr["group"] == "within-domain"]
    cross_row = domain_corr[domain_corr["group"] == "cross-domain"]
    if not within_row.empty and not cross_row.empty:
        lines.append("% ── Domain correlation ──")
        lines += [
            _tex_cmd("WithinDomainMedianCorr", _fmt(float(within_row.iloc[0]["median_spearman"]), 2)),
            _tex_cmd("CrossDomainMedianCorr", _fmt(float(cross_row.iloc[0]["median_spearman"]), 2)),
            _tex_cmd("WithinDomainFracAboveSeven", _pct(float(within_row.iloc[0]["frac_above_0.7"]))),
            _tex_cmd("CrossDomainFracAboveSeven", _pct(float(cross_row.iloc[0]["frac_above_0.7"]))),
        ]
        for _, row in domain_corr.iterrows():
            group = str(row["group"])
            if group.startswith("within: "):
                tag = group.replace("within: ", "").replace(" ", "").replace("&", "And").replace(",", "")
                lines.append(_tex_cmd(f"Within{tag}MedianCorr", _fmt(float(row["median_spearman"]), 2)))
        lines.append("")

    # ── Greedy selection summary ──
    greedy = study_tables["benchmark_greedy_selection"]
    if not greedy.empty:
        lines.append("% ── Greedy benchmark selection ──")
        n_below_07 = int((greedy["max_abs_corr_to_selected"] < 0.7).sum())
        lines += [
            _tex_cmd("GreedyBenchmarksBelowSeven", str(n_below_07)),
        ]
        above_07 = greedy[greedy["max_abs_corr_to_selected"] >= 0.7]
        if not above_07.empty:
            first = above_07.iloc[0]
            lines.append(_tex_cmd("GreedyFirstAboveSeven", str(first["benchmark"])))
            lines.append(_tex_cmd("GreedyFirstAboveSevenStep", str(int(first["step"]))))
        lines.append("")

    # ── HaborMix difficulty composition ──
    lines.append("% ── HaborMix difficulty composition ──")
    tiers = selected_tasks["difficulty_tier"].value_counts().to_dict()
    for tier, count in tiers.items():
        tier_tag = str(tier).capitalize().replace(" ", "")
        lines.append(_tex_cmd(f"HaborMix{tier_tag}Tasks", str(count)))
    lines.append("")

    # ── AIME case study: agent lift by model capability ──
    if raw_benchmark is not None and "aime" in raw_benchmark.columns:
        lines.append("% ── AIME case study ──")
        aime_data = raw_benchmark[["model", "agent", "aime"]].dropna(subset=["aime"])
        case_study_pairs = [
            ("gpt-5.4", "codex", "GptFourCodex"),
            ("gpt-5-mini", "codex", "GptMiniCodex"),
            ("gpt-5-nano", "codex", "GptNanoCodex"),
        ]
        for model, agent, tag in case_study_pairs:
            agent_row = aime_data[(aime_data["model"] == model) & (aime_data["agent"] == agent)]
            base_row = aime_data[(aime_data["model"] == model) & (aime_data["agent"] == BASELINE_AGENT)]
            if not agent_row.empty and not base_row.empty:
                agent_score = float(agent_row.iloc[0]["aime"])
                base_score = float(base_row.iloc[0]["aime"])
                delta_pp = (agent_score - base_score) * 100
                lines += [
                    _tex_cmd(f"Aime{tag}Base", _fmt(base_score, 3)),
                    _tex_cmd(f"Aime{tag}Agent", _fmt(agent_score, 3)),
                    _tex_cmd(f"Aime{tag}DeltaPP", _fmt(delta_pp, 1)),
                ]
        lines.append("")

    # ── Figure paths ──
    fig = "figs/main/quantitative"
    lines.append("% ── Figure paths (all under figs/main/quantitative/) ──")
    lines += [
        _tex_cmd("FigWithinFamilySummary", f"{fig}/within_family_model_vs_agent_summary"),
        _tex_cmd("FigWithinFamilyDetail", f"{fig}/within_family_model_vs_agent_detail"),
        _tex_cmd("FigModelAdjustedEffects", f"{fig}/benchmark_model_adjusted_effects"),
        _tex_cmd("FigAgentLiftHeatmap", f"{fig}/benchmark_agent_lift_heatmap"),
        _tex_cmd("FigTerminusDeltaByModel", f"{fig}/terminus_delta_by_model_heatmap"),
        _tex_cmd("FigHeadroomByDomain", f"{fig}/benchmark_headroom_by_domain"),
        _tex_cmd("FigHeadroomSummary", f"{fig}/benchmark_headroom_tier_summary"),
        _tex_cmd("FigSimilarityHeatmap", f"{fig}/benchmark_similarity_clustered_heatmap"),
        _tex_cmd("FigUniquenessVsCoverage", f"{fig}/benchmark_uniqueness_vs_coverage"),
        _tex_cmd("FigEffectiveDimensionality", f"{fig}/benchmark_effective_dimensionality"),
        _tex_cmd("FigGreedySelection", f"{fig}/benchmark_greedy_selection"),
        _tex_cmd("FigTaskSimilarityHeatmap", f"{fig}/task_similarity_benchmark_pair_heatmap"),
        _tex_cmd("FigTaskPredictability", f"{fig}/task_hard_to_predict_ranked"),
        _tex_cmd("FigTaskRepresentatives", f"{fig}/task_best_representatives"),
        _tex_cmd("FigTaskDifficultyComposition", f"{fig}/task_reliable_difficulty_composition"),
        _tex_cmd("FigHaborMixSelection", f"{fig}/harbormix_selection_diagnostics"),
    ]
    lines.append("")

    import re
    tex = PAPER_TEX_PATH.read_text()
    stats_block = "\n".join(lines)
    replacement = f"% @@STATS_BEGIN@@ — auto-generated by habor-analyze, do not edit manually\n{stats_block}\n% @@STATS_END@@"
    tex = re.sub(
        r"% @@STATS_BEGIN@@.*?% @@STATS_END@@",
        lambda _: replacement,
        tex,
        flags=re.DOTALL,
    )
    PAPER_TEX_PATH.write_text(tex)


APPENDIX_PATH = KEY_REPORT_DIR / "appendix_model_agent.tex"


def write_appendix_model_agent(study_tables: dict[str, pd.DataFrame]) -> None:
    family_summary = study_tables["benchmark_within_family_summary"]
    family_detail = study_tables["benchmark_within_family_model_vs_agent"]
    model_effects = study_tables["benchmark_model_adjusted_effects"]
    agent_effects = study_tables["benchmark_agent_adjusted_effects"]

    lines = [
        r"% Auto-generated by habor-analyze — do not edit manually.",
        r"% Re-generate: uv run habor-analyze studies",
        "",
        r"\subsection{Model vs.\ Agent Effect: Methodology Details}",
        r"\label{app:model-vs-agent}",
        "",
        r"This appendix formalizes the within-family and adjusted-effect analyses",
        r"summarized in the main text.  Let $s(m, a, b)$ denote the",
        r"benchmark score for model~$m$, agent scaffold~$a$, and benchmark~$b$.",
        "",
        r"\subsubsection{Within-Family Comparison}",
        r"\label{app:within-family}",
        "",
        r"For each model provider family $f$ that contains at least two models, let",
        r"$M_f$ be the set of models belonging to $f$ and $A_f$ the set of non-baseline",
        r"agents evaluated on that family.  The baseline agent is Terminus~2.",
        "",
        r"\paragraph{Model effect (fixing agent).}",
        r"For each benchmark~$b$, we fix the agent to Terminus~2 and measure the score",
        r"range across models within the family:",
        r"\begin{equation}",
        r"  \Delta_{\mathrm{model}}^{(f,b)}",
        r"  \;=\;",
        r"  \max_{m \in M_f}\, s(m,\,\text{terminus-2},\,b)",
        r"  \;-\;",
        r"  \min_{m \in M_f}\, s(m,\,\text{terminus-2},\,b).",
        r"  \label{eq:model-effect}",
        r"\end{equation}",
        r"This requires at least two models in~$f$ with observed Terminus~2 scores on~$b$.",
        "",
        r"\paragraph{Agent effect (fixing model).}",
        r"For each model $m \in M_f$ evaluated under both Terminus~2 and another agent",
        r"$a \in A_f$ on benchmark~$b$, we compute the absolute score change:",
        r"\begin{equation}",
        r"  \delta_{\mathrm{agent}}^{(m,a,b)}",
        r"  \;=\;",
        r"  \bigl|\, s(m,\,a,\,b) - s(m,\,\text{terminus-2},\,b) \,\bigr|.",
        r"  \label{eq:agent-delta}",
        r"\end{equation}",
        r"The family-level agent effect on~$b$ averages over all available model--agent pairs:",
        r"\begin{equation}",
        r"  \Delta_{\mathrm{agent}}^{(f,b)}",
        r"  \;=\;",
        r"  \frac{1}{|\mathcal{P}_{f,b}|}",
        r"  \sum_{(m,a)\in \mathcal{P}_{f,b}}",
        r"  \delta_{\mathrm{agent}}^{(m,a,b)},",
        r"  \label{eq:agent-effect}",
        r"\end{equation}",
        r"where $\mathcal{P}_{f,b} = \{(m,a) : m \in M_f,\; a \in A_f,\; \text{both }",
        r"s(m,a,b) \text{ and } s(m,\text{terminus-2},b) \text{ are observed}\}$.",
        "",
        r"\paragraph{Dominance classification.}",
        r"For a given $(f, b)$ pair, the benchmark is classified as",
        r"\emph{model-dominant} if $\Delta_{\mathrm{model}}^{(f,b)} >",
        r"\Delta_{\mathrm{agent}}^{(f,b)}$, and \emph{agent-dominant} otherwise.",
        "",
        r"\paragraph{Family-level summary.}",
        r"We aggregate across benchmarks within each family using the mean:",
        r"\begin{align}",
        r"  \overline{\Delta}_{\mathrm{model}}^{(f)}",
        r"  &= \frac{1}{|B_f|}\sum_{b \in B_f} \Delta_{\mathrm{model}}^{(f,b)}, &",
        r"  \overline{\Delta}_{\mathrm{agent}}^{(f)}",
        r"  &= \frac{1}{|B_f|}\sum_{b \in B_f} \Delta_{\mathrm{agent}}^{(f,b)},",
        r"  \label{eq:family-summary}",
        r"\end{align}",
        r"where $B_f$ is the set of benchmarks with both model-effect and agent-effect",
        r"estimates for family~$f$.  The model-to-agent ratio is",
        r"$\overline{\Delta}_{\mathrm{model}}^{(f)} / \overline{\Delta}_{\mathrm{agent}}^{(f)}$,",
        r"and the model-dominant percentage is the fraction of benchmarks in~$B_f$",
        r"classified as model-dominant.",
        "",
        r"Table~\ref{tab:within-family-summary} reports these statistics for the",
        r"multi-model families.",
        "",
    ]

    # ── Within-family summary table ──
    lines += [
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Within-family model vs.\ agent effect comparison.  The model effect",
        r"    is the score range across models within the family on Terminus~2; the agent",
        r"    effect is the mean absolute score change from switching the agent while",
        r"    holding the model fixed.}",
        r"  \label{tab:within-family-summary}",
        r"  \begin{tabular}{lccccc}",
        r"    \toprule",
        r"    Family",
        r"      & $|\,M_f\,|$",
        r"      & $\overline{\Delta}_{\mathrm{model}}$",
        r"      & $\overline{\Delta}_{\mathrm{agent}}$",
        r"      & Ratio",
        r"      & Model-dom.\ \% \\",
        r"    \midrule",
    ]
    for _, row in family_summary.iterrows():
        fam = str(row["family"])
        n_models = len(MODEL_FAMILIES.get(fam, []))
        me = float(row["model_effect_mean"])
        ae = float(row["agent_effect_mean"])
        ratio = me / ae if ae > 1e-9 else float("inf")
        wins = int(row["model_wins"])
        total = int(row["total_benchmarks"])
        pct = 100 * wins / total if total > 0 else 0
        lines.append(
            f"    {fam} & {n_models} & {me:.3f} & {ae:.3f}"
            f" & {ratio:.1f}$\\times$ & {pct:.0f}\\% \\\\"
        )
    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
        "",
    ]

    # ── Per-family detail tables ──
    for fam_name in ["Anthropic", "OpenAI", "Google"]:
        fam_detail = family_detail[family_detail["family"] == fam_name].sort_values(
            "model_over_agent_ratio", ascending=False
        )
        if fam_detail.empty:
            continue
        models = MODEL_FAMILIES.get(fam_name, [])
        agents_in_fam = [a for a in ["claude-code", "codex", "gemini-cli"]
                         if any(fam_detail["n_agent_pairs"] > 0)]
        lines += [
            r"\begin{table}[t]",
            r"  \centering",
            f"  \\caption{{Per-benchmark within-family comparison for {fam_name}",
            f"    (models: {', '.join(models)}).",
            r"    Model effect is the score range across models on Terminus~2;",
            r"    agent effect is the mean absolute score change from switching agent.}",
            f"  \\label{{tab:within-family-detail-{fam_name.lower()}}}",
            r"  \small",
            r"  \begin{tabular}{lcccc}",
            r"    \toprule",
            r"    Benchmark & $\Delta_{\mathrm{model}}$ & $\Delta_{\mathrm{agent}}$"
            r" & Ratio & Dominant \\",
            r"    \midrule",
        ]
        for _, row in fam_detail.iterrows():
            bname = benchmark_display_name(row["benchmark"])
            me = float(row["model_effect_range"])
            ae = float(row["agent_effect_mean_delta"])
            ratio = float(row["model_over_agent_ratio"])
            dom = str(row["dominant"])
            ratio_str = f"{ratio:.1f}" if ratio < 100 else f"{ratio:.0f}"
            lines.append(
                f"    {bname} & {me:.3f} & {ae:.3f}"
                f" & {ratio_str}$\\times$ & {dom} \\\\"
            )
        lines += [
            r"    \bottomrule",
            r"  \end{tabular}",
            r"\end{table}",
            "",
        ]

    # ── Adjusted effects methodology ──
    lines += [
        r"\subsubsection{Adjusted Group Effects}",
        r"\label{app:adjusted-effects}",
        "",
        r"The within-family analysis is restricted to families with multiple models.  To",
        r"obtain a single ranking across all models and agents, we use adjusted group",
        r"effects that control for confounders via linear regression.",
        "",
        r"Let $\mathbf{y}$ be the vector of benchmark-relative (robustly normalized)",
        r"scores, one entry per observed (model, agent, benchmark) triple.  We fit a",
        r"linear model with confounding factors as one-hot-encoded predictors:",
        r"\begin{equation}",
        r"  \hat{\mathbf{y}} = \mathbf{X}_{\text{controls}}\,\boldsymbol{\beta}.",
        r"  \label{eq:confound-fit}",
        r"\end{equation}",
        "",
        r"\paragraph{Model effects.}",
        r"To estimate adjusted model effects, the controls are \emph{agent} and",
        r"\emph{benchmark} (one-hot encoded, one level dropped per factor):",
        r"\begin{equation}",
        r"  y^{\mathrm{adj}}_i",
        r"  = y_i - \hat{y}_i + \bar{y},",
        r"  \qquad",
        r"  \hat{y}_i = [\mathbf{X}_{\text{agent, benchmark}}\,\hat{\boldsymbol{\beta}}]_i.",
        r"  \label{eq:adjusted-model}",
        r"\end{equation}",
        r"The adjusted model effect is",
        r"$\bar{y}^{\mathrm{adj}}_m = \frac{1}{n_m}\sum_{i:\,\text{model}_i = m}",
        r"y^{\mathrm{adj}}_i$.",
        r"This removes the influence of which agents and benchmarks each model was paired",
        r"with.",
        "",
        r"\paragraph{Agent effects.}",
        r"Symmetrically, to estimate adjusted agent effects, the controls are",
        r"\emph{model} and \emph{benchmark}:",
        r"\begin{equation}",
        r"  y^{\mathrm{adj}}_i",
        r"  = y_i - \hat{y}_i + \bar{y},",
        r"  \qquad",
        r"  \hat{y}_i = [\mathbf{X}_{\text{model, benchmark}}\,\hat{\boldsymbol{\beta}}]_i.",
        r"  \label{eq:adjusted-agent}",
        r"\end{equation}",
        "",
    ]

    # ── Adjusted model effects table ──
    lines += [
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Adjusted model effects.  Each model's mean benchmark-relative score",
        r"    is adjusted by removing the confounding effect of which agents and",
        r"    benchmarks it was paired with.  Units are robust-scaled benchmark-relative",
        r"    scores (0~=~benchmark median).}",
        r"  \label{tab:adjusted-model-effects}",
        r"  \begin{tabular}{lcc}",
        r"    \toprule",
        r"    Model & Adjusted mean & Observations \\",
        r"    \midrule",
    ]
    for _, row in model_effects.iterrows():
        lines.append(
            f"    {row['model']} & {float(row['adjusted_mean']):+.3f}"
            f" & {int(row['observations'])} \\\\"
        )
    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
        "",
    ]

    # ── Adjusted agent effects table ──
    lines += [
        r"\begin{table}[t]",
        r"  \centering",
        r"  \caption{Adjusted agent effects.  Same methodology as",
        r"    Table~\ref{tab:adjusted-model-effects}, controlling for model and",
        r"    benchmark.}",
        r"  \label{tab:adjusted-agent-effects}",
        r"  \begin{tabular}{lcc}",
        r"    \toprule",
        r"    Agent & Adjusted mean & Observations \\",
        r"    \midrule",
    ]
    for _, row in agent_effects.iterrows():
        lines.append(
            f"    {row['agent']} & {float(row['adjusted_mean']):+.3f}"
            f" & {int(row['observations'])} \\\\"
        )
    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
        "",
    ]

    APPENDIX_PATH.parent.mkdir(parents=True, exist_ok=True)
    APPENDIX_PATH.write_text("\n".join(lines) + "\n")


KEY_TABLE_SUBDIRS = {
    "analysis_data_provenance": "provenance",
    "imputation_diagnostics_summary": "provenance",
    "benchmark_agent_model_scores": "leaderboards",
    "benchmark_scores_long": "leaderboards",
    "benchmark_mini_leaderboards": "leaderboards",
    "task_benchmark_reliable_summary": "task_level",
    "task_to_benchmark_alignment": "task_level",
    "task_within_benchmark_similarity": "task_level",
    "task_cross_benchmark_similarity": "task_level",
    "task_representative_tasks": "task_level",
    "task_predictability_ranked": "task_level",
    "harbormix_selected_tasks": "harbormix",
    "harbormix_selection_by_benchmark": "harbormix",
    "terminus_delta_by_model": "benchmark_level",
}


def key_table_path(name: str) -> Path:
    subdir = KEY_TABLE_SUBDIRS.get(name, "benchmark_level" if name.startswith("benchmark") else "task_level")
    return KEY_TABLE_DIR / subdir / f"{name}.csv"


def write_key_analysis_reports(
    study_tables: dict[str, pd.DataFrame],
    benchmark_result: ImputationResult,
    task_result: ImputationResult,
    included_benchmarks: list[str],
    mini_leaderboard_figures: list[str],
) -> None:
    filter_table = study_tables["benchmark_filtering"]
    provenance = study_tables["analysis_data_provenance"]
    imputation_diagnostics = study_tables["imputation_diagnostics_summary"]
    agent_model_scores = study_tables["benchmark_agent_model_scores"]
    model_effects = study_tables["benchmark_model_adjusted_effects"]
    agent_effects = study_tables["benchmark_agent_adjusted_effects"]
    family_detail = study_tables["benchmark_within_family_model_vs_agent"]
    family_summary = study_tables["benchmark_within_family_summary"]
    benchmark_clusters = study_tables["benchmark_similarity_clusters"]
    redundancy = study_tables["benchmark_redundancy_pairs_filtered"]
    domain_corr_summary = study_tables["benchmark_domain_correlation_summary"]
    dim_stats = study_tables["benchmark_effective_dimensionality"]
    greedy_selection = study_tables["benchmark_greedy_selection"]
    uniqueness = study_tables["benchmark_uniqueness_filtered"]
    agent_lift = study_tables["benchmark_agent_lift_vs_terminus"]
    terminus_by_model = study_tables["terminus_delta_by_model"]
    task_summary = study_tables["task_benchmark_reliable_summary"]
    alignment = study_tables["task_to_benchmark_alignment"]
    task_similarity = study_tables["task_within_benchmark_similarity"]
    task_cross_similarity = study_tables["task_cross_benchmark_similarity"]
    representative_tasks = study_tables["task_representative_tasks"]
    task_predictability = study_tables["task_predictability_ranked"]
    selected_tasks = study_tables["harbormix_selected_tasks"]
    selection_by_benchmark = study_tables["harbormix_selection_by_benchmark"]
    task_imputation_cv = task_result.cv.sort_values(["mae", "rmse", "rank"], na_position="last").copy()
    best_task_imputer = str(task_imputation_cv.iloc[0]["method"])
    best_task_rank = int(task_imputation_cv.iloc[0]["rank"])

    excluded = filter_table[~filter_table["include_in_key_analysis"]]
    redundant_high = redundancy[redundancy["spearman"] >= 0.75].sort_values("spearman", ascending=False)
    unique_low = uniqueness.sort_values("cv_r2_from_other_included_benchmarks")
    alignment_good = alignment[
        alignment["included_in_benchmark_level_key_filter"] & (alignment["n_reliable_bounded_tasks"] >= 3)
    ].sort_values("spearman_agent_model_correlation", ascending=False)
    task_pool = task_summary.sort_values("candidate_pool_tasks", ascending=False)
    hard_tasks = task_predictability.sort_values("task_unpredictability_score", ascending=False)
    representative_top = representative_tasks.sort_values("useful_representativeness_score", ascending=False)
    predictable_benchmarks = uniqueness.sort_values("cv_r2_from_other_included_benchmarks", ascending=False)
    story_unique_benchmarks = ", ".join(unique_low["benchmark"].head(5).tolist())
    story_predictable_benchmarks = ", ".join(predictable_benchmarks["benchmark"].head(5).tolist())
    story_hard_tasks = ", ".join((hard_tasks["benchmark"] + "/" + hard_tasks["task_id"]).head(3).tolist())
    story_representative_tasks = ", ".join(
        (representative_top["benchmark"] + "/" + representative_top["task_id"]).head(3).tolist()
    )
    selected_tiers = selected_tasks["difficulty_tier"].value_counts().to_dict()
    selected_tier_summary = ", ".join(f"{tier}: {count}" for tier, count in selected_tiers.items())
    key_tables = sorted(str(path.relative_to(KEY_TABLE_DIR)) for path in KEY_TABLE_DIR.rglob("*.csv"))
    all_key_figures = sorted(str(path.relative_to(KEY_FIGURE_DIR)) for path in KEY_FIGURE_DIR.rglob("*.png"))
    key_figures = [name for name in all_key_figures if not name.startswith("leaderboards/per_benchmark/")]
    per_benchmark_leaderboard_count = len(all_key_figures) - len(key_figures)
    code_files = [
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'core')}/`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'preprocessing' / 'svd_imputation.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'coverage_filtering.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'intermediate_tables.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'model_agent_roles.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'benchmark_predictability.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'benchmark_similarity.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'leaderboards.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'terminus_comparison.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'task_alignment.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'task_selection.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'task_similarity.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'studies' / 'provenance.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'visualization')}/`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'reporting' / 'key_analysis_report.py')}`",
        f"- `{md_path(ROOT / 'src' / 'habor_mix_analyzer' / 'cli.py')}`",
    ]

    report_lines = [
        "# Key Analysis Cross-Benchmark Analysis",
        "",
        "This report is intended to be read directly. Figures and compact table previews are embedded inline; CSV paths are listed for exact numbers and reproducibility.",
        "",
        "## Directory Contract",
        "",
        f"- Key analysis tables: `{md_path(KEY_TABLE_DIR)}/`",
        f"- Key analysis figures: `{md_path(KEY_FIGURE_DIR)}/`",
        "- Layered table groups: `benchmark_level/`, `leaderboards/`, `task_level/`, `harbormix/`, and `provenance/`.",
        "- Layered figure groups: `benchmark_level/`, `leaderboards/`, `task_level/`, and `harbormix/`.",
        "- Leaderboard figures are further layered into `leaderboards/per_benchmark/` and `leaderboards/clustered/`; the report embeds only the clustered pages to keep reading compact.",
        f"- Intermediate study outputs: `{md_path(INTERMEDIATE_STUDY_DIR)}/`",
        f"- Intermediate imputed matrices and diagnostics: `{md_path(PROCESSED_DIR)}/`",
        "",
        "The current preprocessing contract is task-first: task scores are filled first, then benchmark scores are aggregated from the filled task matrix. The original benchmark matrix is retained as metadata and as a sanity check, but benchmark scores are not imputed directly.",
        "",
        "BenchPress mapping note: Dimitris's BenchPress repo treats benchmark prediction as an explicit analysis problem, compares benchmark-regression and SVD families under held-out validation, and uses a blend because regression can be more accurate while SVD gives broader coverage. Our schema is task-rich rather than model-benchmark-only, so we map that lesson by validating several task-fill families on held-out observed cells, using benchmark/task predictability tables for difficulty ranking, and keeping task aggregate alignment as a diagnostic rather than blindly trusting every aggregate.",
        "",
        "Data provenance for the main studies:",
        "",
        *markdown_table(provenance, ["analysis", "primary_matrix", "processed_output"], 10),
        "",
        "Preprocessing diagnostics:",
        "",
        f"Task imputation method: each score column is robustly centered and scaled after `log1p` for nonnegative unbounded columns. The pipeline compares column-median, row-mean shrinkage, two-way shrinkage, and low-rank iterative SVD candidates on held-out observed cells, then uses the lowest-MAE method. For this run the selected task imputer is `{best_task_imputer}` with rank {best_task_rank}. Observed task cells are restored exactly; filled task scores are inverse-transformed and clipped to the observed range of that task. Benchmark scores are then calculated as per-benchmark means across those task scores. Task-level imputation remains less stable than dense benchmark tables because the task matrix is much wider and sparser, so task conclusions are restricted to reliable bounded non-degenerate tasks.",
        "",
        *markdown_table(
            imputation_diagnostics,
            [
                "matrix",
                "preprocessing_method",
                "selected_imputation_method",
                "missing_fraction_before_processing",
                "selected_imputation_rank",
                "task_imputation_method_used_for_benchmark_aggregation",
                "task_imputation_rank_used_for_benchmark_aggregation",
                "holdout_cells",
                "holdout_rmse_scaled_score_space",
                "holdout_mae_scaled_score_space",
            ],
            4,
        ),
        "",
        "Held-out task imputation comparison:",
        "",
        *markdown_table(task_imputation_cv, ["method", "rank", "holdout_cells", "rmse", "mae"], 10),
        "",
        "Interpretation: the task matrix is sparse and very wide, so this is a validation-backed fill, not ground truth. The aggregate benchmark table is more stable than individual filled cells because it averages over many task columns, but sparse benchmarks should still be read with their task-cell missingness fields.",
        "",
        "Reliability conclusion: SVD is not automatically the right fill here. In this run, low-rank SVD improves RMSE because it reduces a few large scaled errors, but it loses on MAE, which is the better primary criterion for this mixed-scale sparse matrix because many robust-normalized task columns have outlier-sensitive tails. The selected column-median fill is therefore intentionally conservative: it preserves each task's observed center and avoids hallucinating row-level structure where the held-out cells do not support it.",
        "",
        "## Research Question Coverage Checklist",
        "",
        "| Question | Status | Main artifacts |",
        "| --- | --- | --- |",
        "| Agent vs model role overall and per benchmark | covered | `tables/benchmark_level/benchmark_within_family_model_vs_agent.csv`, `tables/benchmark_level/benchmark_within_family_summary.csv`, `figures/benchmark_level/within_family_model_vs_agent_summary.png` |",
        "| BenchPress-style benchmark predictability and hard-to-predict benchmarks/tasks | covered | `tables/benchmark_level/benchmark_uniqueness_filtered.csv`, `tables/task_level/task_predictability_ranked.csv`, benchmark/task predictability figures |",
        "| Benchmark/task similarity and clustering | covered | `tables/benchmark_level/benchmark_similarity_clusters.csv`, `tables/task_level/task_cross_benchmark_similarity.csv`, clustered heatmaps |",
        "| Representative tasks per benchmark | covered | `tables/task_level/task_representative_tasks.csv`, `figures/task_level/task_best_representatives.png` |",
        "| Mini-leaderboards grouped by similar benchmarks | covered | `tables/leaderboards/benchmark_mini_leaderboards.csv`, `figures/leaderboards/clustered/mini_leaderboards_cluster_*.png` |",
        "| Agent harness improvements over Terminus | covered | `tables/benchmark_level/benchmark_agent_lift_vs_terminus.csv`, `tables/benchmark_level/terminus_delta_by_model.csv`, Terminus heatmaps |",
        "| Quantitative HaborMix task selection | covered | `tables/harbormix/harbormix_selected_tasks.csv`, `tables/harbormix/harbormix_selection_by_benchmark.csv`, `figures/harbormix/harbormix_selection_diagnostics.png` |",
        "",
        "## Study 1: Coverage Filtering",
        "",
        "**Method:** Benchmark-level claims use benchmark aggregates derived from the filled task matrix, but coverage filtering still uses evidence metadata: at least 15 agent+model rows need some observed task evidence for that benchmark, and the missingness fields describe coverage before task filling. This filter keeps the key analysis story from leaning too heavily on filled task values.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_filtering'))}`",
        "",
        "**Result overview and analysis:**",
        f"- Included {len(included_benchmarks)} of {len(filter_table)} benchmarks.",
        f"- Excluded sparse benchmarks: {', '.join(excluded['benchmark'].tolist())}.",
        f"- Benchmark scores are task aggregates, not direct benchmark-imputation outputs; pre-aggregation benchmark missing fraction was {benchmark_result.missing_fraction:.3f}.",
        "",
        *markdown_table(filter_table, ["benchmark", "include_in_key_analysis", "observed_count", "missing_fraction", "task_cell_missing_fraction"], 12),
        "",
        "**Insight and findings:** Sparse columns should stay in appendix/provisional analysis until more experiments land. The main key analysis story should use the coverage-filtered benchmark set.",
        "",
        "## Study 2: Model vs Agent Roles",
        "",
        "**Method:** Within-family analysis compares model effect (score range across models in the same family, fixing agent to terminus-2) against agent effect (score delta from switching agent, fixing model). This is computed per (family, benchmark) pair and aggregated per family.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_within_family_model_vs_agent'))}`",
        f"- `{md_path(key_table_path('benchmark_within_family_summary'))}`",
        f"- `{md_path(key_table_path('benchmark_model_adjusted_effects'))}`",
        f"- `{md_path(key_table_path('benchmark_agent_adjusted_effects'))}`",
        "",
        report_image("benchmark_level/within_family_model_vs_agent_summary.png", "Within-family model vs agent effect size"),
        "",
        report_image("benchmark_level/within_family_model_vs_agent_detail.png", "Within-family model vs agent effect by benchmark"),
        "",
        report_image("benchmark_level/benchmark_model_adjusted_effects.png", "Model effects adjusted for agent and benchmark"),
        "",
        report_image("benchmark_level/benchmark_agent_adjusted_effects.png", "Agent effects adjusted for model and benchmark"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(family_summary, ["family", "model_effect_median", "agent_effect_median", "model_wins", "total_benchmarks"], 10),
        "",
        "**Insight and findings:** Across all families with multiple models, switching model produces larger score changes than switching agent on the majority of benchmarks. The effect is strongest for Anthropic (model effect ~4x agent effect) and consistent for OpenAI (model wins 70% of benchmarks).",
        "",
        "## Study 3: Agent+Model Leaderboards",
        "",
        "**Method:** I keep `agent+model` rankings as descriptive mini-leaderboards. Per-benchmark mini-leaderboards use benchmark scores aggregated from filled tasks on each benchmark's original metric scale. Each mini-leaderboard shows all available agent+model rows, grouped by model with colored bars for agents, so the same plot makes model differences and agent harness differences visible. The aggregate top-agent plot uses mean within-benchmark score percentile, because averaging scores across benchmarks with different scales would be misleading.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_agent_model_scores'))}`",
        f"- `{md_path(key_table_path('benchmark_scores_long'))}`",
        f"- `{md_path(key_table_path('benchmark_mini_leaderboards'))}`",
        f"- `{md_path(key_table_path('benchmark_similarity_clusters'))}`",
        f"- `{md_path(KEY_FIGURE_DIR / 'leaderboards' / 'clustered' / 'mini_leaderboards_cluster_*.png')}`",
        f"- `{md_path(KEY_FIGURE_DIR / 'leaderboards' / 'per_benchmark' / 'mini_leaderboard_*.png')}`",
        "",
        report_image("leaderboards/benchmark_agent_model_top_scores.png", "Top agent+model pairs on included benchmarks"),
        "",
        *[report_image(fig, f"Mini-leaderboards {fig}") for fig in mini_leaderboard_figures],
        "",
        "**Result overview and analysis:**",
        *markdown_table(agent_model_scores, ["rank", "agent_model", "mean_score_percentile_across_benchmarks", "original_benchmark_table_coverage"], 10),
        "",
        "**Insight and findings:** Benchmark scores should be read benchmark by benchmark. The percentile aggregate is a compact descriptive ranking only; it is not a causal agent claim because model and agent are entangled in the row identity.",
        "",
        "## Study 4: How Correlated Are Benchmarks?",
        "",
        "### 4.1 Effective Dimensionality",
        "",
        f"**Method:** PCA on the full normalized benchmark score matrix ({len(included_benchmarks)} included benchmarks). "
        "The participation ratio (PR = (Σλ)² / Σλ²) measures how many components carry meaningful variance — "
        "a PR of k means the suite behaves like k independent benchmarks.",
        "",
        report_image("benchmark_level/benchmark_effective_dimensionality.png", "Effective dimensionality: scree and cumulative variance"),
        "",
        f"**Result:** {len(included_benchmarks)} benchmarks collapse to ~{dim_stats.iloc[0]['participation_ratio']:.0f} effective independent dimensions "
        f"(participation ratio). The first component alone explains {dim_stats.iloc[0]['top1_variance']:.1%} of variance; "
        f"{int(dim_stats.iloc[0]['n_components_90pct'])} components reach 90%, "
        f"{int(dim_stats.iloc[0]['n_components_95pct'])} reach 95%.",
        "",
        "### 4.2 Domain-Aware Correlation Structure",
        "",
        "**Method:** Every benchmark pair is labeled within-domain or cross-domain (using the domain taxonomy in `config.py`). "
        "We compare the Spearman correlation distributions to quantify how much domain grouping explains the correlation structure.",
        "",
        report_image("benchmark_level/benchmark_domain_correlation_comparison.png", "Within- vs cross-domain correlation distributions"),
        "",
        report_image("benchmark_level/benchmark_correlation_by_domain.png", "Domain-grouped benchmark correlation heatmap"),
        "",
        "**Result:**",
        *markdown_table(domain_corr_summary, ["group", "n_pairs", "mean_spearman", "median_spearman", "frac_above_0.7"], 15),
        "",
        "### 4.3 Benchmark Predictability",
        "",
        "**Method:** BenchPress-style predictability (adapted from Dimitris's BenchPress repo). "
        "For each model, 50% of its known scores are hidden; the remaining scores are used to predict the hidden cells "
        "via BenchPress = 0.6 × LogitBenchReg (top-5 correlated benchmarks, ridge regression in logit space) + "
        "0.4 × SVD-Logit (rank-2 soft-impute in logit space). Per-benchmark median absolute error on held-out cells "
        "measures predictability: higher error means the benchmark carries more unique signal.",
        "",
        report_image("benchmark_level/benchmark_uniqueness_vs_coverage.png", "Benchmark predictability ranking (BenchPress holdout error)"),
        "",
        "Hardest-to-predict benchmarks (highest holdout error):",
        *markdown_table(unique_low, ["benchmark", "cv_r2_from_other_included_benchmarks", "cv_rmse"], 10),
        "",
        "Most similar benchmark pairs:",
        *markdown_table(redundant_high, ["left", "right", "spearman"], 10),
        "",
        "### 4.4 Greedy Benchmark Selection",
        "",
        "**Method:** Starting from the most independent benchmark (lowest mean |correlation| to all others), "
        "greedily add the benchmark whose max |correlation| to the already-selected set is smallest. "
        "This orders benchmarks from most to least independently informative.",
        "",
        report_image("benchmark_level/benchmark_greedy_selection.png", "Greedy benchmark selection order"),
        "",
        "### 4.5 Data-Driven Clustering",
        "",
        report_image("benchmark_level/benchmark_similarity_clustered_heatmap.png", "Clustered benchmark similarity heatmap"),
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_uniqueness_filtered'))}`",
        f"- `{md_path(key_table_path('benchmark_redundancy_pairs_filtered'))}`",
        f"- `{md_path(key_table_path('benchmark_correlation_clustered'))}`",
        f"- `{md_path(key_table_path('benchmark_domain_correlation_summary'))}`",
        f"- `{md_path(key_table_path('benchmark_effective_dimensionality'))}`",
        f"- `{md_path(key_table_path('benchmark_greedy_selection'))}`",
        "",
        f"**Insight and findings:** The {len(included_benchmarks)} benchmarks carry ~{dim_stats.iloc[0]['participation_ratio']:.0f} effective independent dimension of variation (participation ratio), "
        f"with PC1 alone explaining {dim_stats.iloc[0]['top1_variance']:.0%} of variance — a dominant 'general capability' factor ranks systems similarly across most benchmarks. "
        "Within-domain benchmarks are more correlated than cross-domain pairs, but domain alone does not explain all overlap: "
        "some cross-domain pairs correlate highly because they tap shared model capabilities. "
        "High correlation does NOT mean one benchmark can substitute for another — each benchmark still tests domain-specific skills "
        "and has independent value for diagnosing system strengths and weaknesses within its domain. "
        "Correlation tells us about the amount of independent ranking information, not about interchangeability. "
        f"The least reconstructable benchmarks are {story_unique_benchmarks}. "
        f"The most predictable are {story_predictable_benchmarks}.",
        "",
        "## Study 5: Task Similarity, Predictability, and Representatives",
        "",
        "**Method:** Task-level analysis uses reliable, bounded, non-degenerate tasks only. Task similarity also uses same-dimensional vectors: every task is represented by its filled, standardized score profile across the same agent+model rows. A task is hard to predict when its maximum absolute profile correlation to peer tasks in the same benchmark is low. Representativeness is no longer pure correlation with the benchmark aggregate: I compute a leave-one-out aggregate correlation and multiply it by observed cross-agent/model variance, so redundant but low-discrimination tasks no longer dominate. Within- and cross-benchmark task similarity use median absolute task-profile correlations, with at most the most discriminative 40 tasks sampled per benchmark for cross-benchmark pair summaries. Difficulty tiers use mean task score thresholds: frontier <5%, hard 5-30%, medium 30-70%, easy 70-95%, saturated >95%.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('task_predictability_ranked'))}`",
        f"- `{md_path(key_table_path('task_representative_tasks'))}`",
        f"- `{md_path(key_table_path('task_within_benchmark_similarity'))}`",
        f"- `{md_path(key_table_path('task_cross_benchmark_similarity'))}`",
        "",
        report_image("task_level/task_hard_to_predict_ranked.png", "Hard-to-predict reliable tasks"),
        "",
        report_image("task_level/task_best_representatives.png", "Best representative task per benchmark"),
        "",
        report_image("task_level/task_similarity_benchmark_pair_heatmap.png", "Task similarity across benchmark pairs"),
        "",
        "**Result overview and analysis:**",
        "Hardest-to-predict reliable tasks:",
        *markdown_table(hard_tasks, ["benchmark", "task_id", "task_unpredictability_score", "difficulty_tier", "task_score"], 12),
        "",
        "Most representative tasks:",
        *markdown_table(representative_top, ["benchmark", "task_id", "useful_representativeness_score", "representativeness_score", "difficulty_tier", "task_score"], 12),
        "",
        "Benchmarks with strongest within-benchmark task similarity:",
        *markdown_table(task_similarity, ["benchmark", "n_reliable_tasks", "median_abs_task_similarity_within_benchmark"], 10),
        "",
        "**Insight and findings:** Task predictability and useful representativeness are different objectives. Representative tasks are the base set for predicting benchmark aggregates; hard-to-predict and difficult tasks are additional stress tests for broad coverage.",
        "",
        f"Paper-facing read: the hardest-to-predict task examples begin with {story_hard_tasks}. The most useful representative task examples begin with {story_representative_tasks}. That split is the main reason HaborMix should not be selected from one scalar alone: a task can be representative without being unique, and a unique task can be too idiosyncratic to stand in for its benchmark.",
        "",
        "## Study 6: Terminus Harnessing Effects",
        "",
        "**Method:** Terminus is treated as the fair baseline across models. For every model with both `terminus-2` and another agent row, I compute paired benchmark-relative score deltas while holding the model fixed.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('benchmark_agent_lift_vs_terminus'))}`",
        f"- `{md_path(key_table_path('terminus_delta_by_model'))}`",
        f"- `{md_path(BENCHMARK_INTERMEDIATE_STUDY_DIR / 'benchmark_agent_lift_by_benchmark.csv')}`",
        "",
        report_image("benchmark_level/benchmark_agent_lift_heatmap.png", "Agent lift vs terminus by benchmark"),
        "",
        report_image("benchmark_level/terminus_delta_by_model_heatmap.png", "Agent lift vs terminus by model"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(agent_lift, ["agent", "mean_delta_vs_terminus", "win_rate_vs_terminus", "compared_models"], 6),
        "",
        *markdown_table(terminus_by_model, ["model", "agent", "mean_delta_vs_terminus", "win_rate_vs_terminus"], 12),
        "",
        "**Insight and findings:** Paired deltas are the best current evidence for whether an agent harness improves over Terminus. The deltas vary by model and benchmark, so claims should avoid saying one harness universally dominates.",
        "",
        "## Study 7: HaborMix Selection",
        "",
        "**Method:** Candidate tasks must be reliable and bounded. The final HaborMix selection targets a compact 100-200 task set, currently 160 tasks. It first includes a small base set of useful representative tasks per benchmark, then fills the remaining slots with a diversity-aware ranking over difficult, frontier-with-variance, unique/unpredictable, and high-composite tasks. The composite score combines useful representativeness, difficulty, unique/unpredictable signal, and cross-agent/model discrimination; it no longer excludes frontier or saturated items by construction. The broader scored pool is retained under intermediate studies for auditability.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('harbormix_selected_tasks'))}`",
        f"- `{md_path(key_table_path('harbormix_selection_by_benchmark'))}`",
        f"- `{md_path(TASK_INTERMEDIATE_STUDY_DIR / 'harbormix_scored_task_pool.csv')}`",
        f"- `{md_path(TASK_INTERMEDIATE_STUDY_DIR / 'task_frontier_or_saturated_watchlist.csv')}`",
        "",
        report_image("harbormix/harbormix_selection_diagnostics.png", "HaborMix selection diagnostics"),
        "",
        report_image("task_level/task_reliable_difficulty_composition.png", "Reliable bounded task difficulty composition"),
        "",
        report_image("task_level/task_reliable_difficulty_composition_percent.png", "Reliable bounded task difficulty composition by percentage"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(selection_by_benchmark, ["benchmark", "difficulty_tier", "selected_tasks", "mean_selection_score", "mean_representative_signal", "mean_unique_unpredictable_signal", "mean_difficulty_signal"], 14),
        "",
        f"- Selected {len(selected_tasks)} final HaborMix tasks from the broader scored candidate pool.",
        "",
        "**Insight and findings:** HaborMix selection is quantitative and auditable: representative tasks anchor the minimal benchmark-prediction base, while difficult and unique/unpredictable tasks add breadth.",
        "",
        f"Paper-facing read: the final {len(selected_tasks)}-task set is intentionally not just a hard-task list. Its difficulty composition is {selected_tier_summary}. The base representative set keeps each included benchmark anchored to its aggregate behavior, while the diversity-aware fill adds difficult, frontier, and uniquely informative items.",
        "",
        "## Study 8: Task Aggregate vs Benchmark-Level Score Alignment",
        "",
        "**Method:** For each benchmark, I average benchmark-relative task scores and correlate that aggregate with the benchmark-level benchmark-relative score across agent+model rows. This is intentionally diagnostic rather than a hard gate: the new benchmark score is already the task aggregate, so this table mainly identifies benchmarks where reliable bounded tasks alone do or do not track the full task-derived benchmark aggregate.",
        "",
        "**Code files:**",
        *code_files,
        "",
        "**Result paths:**",
        f"- `{md_path(key_table_path('task_to_benchmark_alignment'))}`",
        "",
        report_image("task_level/task_to_benchmark_alignment.png", "Task aggregate vs benchmark score alignment"),
        "",
        "**Result overview and analysis:**",
        *markdown_table(alignment_good, ["benchmark", "n_reliable_bounded_tasks", "spearman_agent_model_correlation", "alignment_quality"], 12),
        "",
        "**Insight and findings:** Strong alignment means the reliable bounded subset is a good proxy for the task-derived benchmark score. Weak alignment is not used to remove benchmarks automatically; it flags cases for manual benchmark/task inspection.",
        "",
        "## Cross-Study Story",
        "",
        "The emerging story is that benchmark diversity matters more than a single aggregate leaderboard. Coverage filtering removes sparse columns from the main benchmark-level claims, and the imputation diagnostic makes the same point from the preprocessing side: the data are dense only after filling, and the selected fill is conservative because held-out validation did not justify stronger SVD structure by MAE.",
        "",
        "Within the retained benchmarks, model identity is usually more impactful than agent identity. Within-family analysis shows that switching model produces larger score changes than switching agent on the majority of benchmarks across all major model families. The report keeps descriptive `agent+model` leaderboards for browsing, but uses paired Terminus deltas when making harness claims.",
        "",
        f"The BenchPress-style predictability layer identifies a preservation/compression axis. Benchmarks such as {story_unique_benchmarks} are hard to reconstruct and therefore carry distinctive signal. Benchmarks such as {story_predictable_benchmarks} are easier to reconstruct and can be grouped more aggressively. The clustered heatmaps and clustered mini-leaderboards give the visual version of the same argument.",
        "",
        "The task layer answers a different selection problem. Representative tasks are useful as small proxies for benchmark aggregates; unpredictable and difficult tasks are useful as stress tests. HaborMix combines those roles by taking representative base tasks first, then filling with difficult, unique, and discriminative tasks until the final compact set reaches the target size range. That is the clearest story for why HaborMix is not merely a random subset, not merely a hard subset, and not merely a redundant set of benchmark prototypes.",
        "",
        "## Artifact Index",
        "",
        "All key analysis tables:",
        *[f"- `{md_path(KEY_TABLE_DIR / name)}`" for name in key_tables],
        "",
        "All key analysis figures:",
        *[f"- `{md_path(KEY_FIGURE_DIR / name)}`" for name in key_figures],
        f"- `{md_path(KEY_FIGURE_DIR / 'leaderboards' / 'per_benchmark')}/` ({per_benchmark_leaderboard_count} per-benchmark mini-leaderboard files, listed by directory rather than expanded here)",
        "",
        "## Not Completed Yet",
        "",
        "- Trial reliability, pass@k, efficiency curves, token/tool cost analysis, and trajectory failure taxonomy still require per-trial run records.",
        "- Full IRT/DIF still requires repeated binary/calibrated task outcomes or enough dense task observations to fit stable item-response models.",
        "- Provider scaling analysis still requires external model metadata such as provider family, parameter scale, release date, and inference budget.",
        "",
    ]
    (KEY_REPORT_DIR / "analysis_story.md").write_text("\n".join(report_lines))

    findings_lines = [
        "# Key Findings for Key Analysis Drafting",
        "",
        f"0. The processed benchmark matrix is task-first and uses `{best_task_imputer}` task filling, not direct benchmark imputation.",
        "",
        "Benchmark scores are simple means over the filled task matrix. The imputation reliability check compares candidate task fillers on held-out observed cells; SVD has lower RMSE here but higher MAE, so the selected fill is conservative rather than low-rank.",
        "",
        *markdown_table(task_imputation_cv, ["method", "rank", "holdout_cells", "rmse", "mae"], 5),
        "",
        f"1. Use {len(included_benchmarks)} coverage-filtered benchmarks for benchmark-level claims; keep sparse benchmarks in appendix/provisional analysis.",
        "",
        "The filtering table is now evidence-based on the task-first pipeline: benchmark scores come from filled-task aggregates, while the missingness columns describe how much original task evidence supported each aggregate before filling.",
        "",
        report_image("benchmark_level/benchmark_uniqueness_vs_coverage.png", "Benchmark predictability ranking"),
        "",
        *markdown_table(filter_table, ["benchmark", "include_in_key_analysis", "observed_count", "task_cell_missing_fraction"], 8),
        "",
        "2. Model identity is the larger overall factor. Within-family analysis shows switching model produces larger score changes than switching agent across the majority of benchmarks.",
        "",
        report_image("benchmark_level/within_family_model_vs_agent_summary.png", "Within-family model vs agent effect size"),
        "",
        *markdown_table(family_summary, ["family", "model_effect_median", "agent_effect_median", "model_wins", "total_benchmarks"], 8),
        "",
        "3. Separate model and agent dimensions. The useful agent evidence is paired lift over `terminus-2` for the same model, not an unqualified agent+model leaderboard.",
        "",
        "The Terminus table should be read as a harnessing-effect estimate: the paired comparison holds model fixed where the same model appears under Terminus and another agent.",
        "",
        report_image("benchmark_level/terminus_delta_by_model_heatmap.png", "Agent lift vs terminus by model"),
        "",
        *markdown_table(agent_lift, ["agent", "mean_delta_vs_terminus", "win_rate_vs_terminus", "compared_models"], 6),
        "",
        "4. BenchPress-style predictability applies here: redundant benchmarks can be compressed; least-predictable benchmarks should be preserved for behavioral breadth.",
        "",
        "The benchmark-predictability result is deliberately separate from clustering: regression asks whether other benchmarks reconstruct a target, while the heatmap shows score-profile similarity. Use both when deciding whether two benchmarks are redundant.",
        "",
        report_image("benchmark_level/benchmark_similarity_clustered_heatmap.png", "Clustered benchmark similarity heatmap"),
        "",
        *markdown_table(unique_low, ["benchmark", "cv_r2_from_other_included_benchmarks", "cv_rmse"], 8),
        "",
        "5. Task predictability and task representativeness are distinct: hard-to-predict tasks are stress tests, while representative tasks are compact proxies for a benchmark.",
        "",
        "The representative-task score now uses leave-one-out aggregate correlation times task variance, so tasks that are merely typical but non-discriminative are less likely to dominate the selected base set.",
        "",
        report_image("task_level/task_hard_to_predict_ranked.png", "Hard-to-predict reliable tasks"),
        "",
        report_image("task_level/task_best_representatives.png", "Best representative task per benchmark"),
        "",
        *markdown_table(hard_tasks, ["benchmark", "task_id", "task_unpredictability_score", "difficulty_tier"], 8),
        "",
        *markdown_table(representative_top, ["benchmark", "task_id", "useful_representativeness_score", "difficulty_tier"], 8),
        "",
        f"6. The current HaborMix final set contains {len(selected_tasks)} diversified tasks.",
        "",
        "The HaborMix scorer is no longer centered on moderate difficulty. It first takes useful representative base tasks, then fills to a compact target size with difficult, frontier-with-variance, unique/unpredictable, and high-composite tasks.",
        "",
        report_image("harbormix/harbormix_selection_diagnostics.png", "HaborMix selection diagnostics"),
        "",
        *markdown_table(selection_by_benchmark, ["benchmark", "difficulty_tier", "selected_tasks", "mean_selection_score"], 10),
        "",
        "7. Task-to-benchmark alignment should be used as a sanity check before interpreting benchmark-level scores from task-level tables.",
        "",
        "This table is diagnostic rather than a gate. Weak alignment means the reliable bounded subset may not proxy the full task-derived aggregate well; it does not automatically remove the benchmark from the benchmark-level analysis.",
        "",
        report_image("task_level/task_to_benchmark_alignment.png", "Task aggregate vs benchmark score alignment"),
        "",
        *markdown_table(alignment_good, ["benchmark", "n_reliable_bounded_tasks", "spearman_agent_model_correlation", "alignment_quality"], 8),
        "",
        "Primary reference file: `output/key_analyses/reports/analysis_story.md`.",
    ]
    (KEY_REPORT_DIR / "key_findings.md").write_text("\n".join(findings_lines))
